version: '3.8'

services:
  expo-app:
    build: .
    container_name: sinanozturk.dev
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=development
    volumes:
      # Geliştirme için hot reload için volume mount
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true 