name: sinanozturk

services:
  sinanozturk-web:
    build: .
    image: sinanozturk-web:latest
    container_name: sinanozturk-web
    ports:
      - "1998:8081"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 